name: CompanySystem-iOS
include:
  - xcodegen_ng_templates.yml

targets:
  CompanySystem-iOS:
    templates:
      - application
    sources:
      - App
    scheme:
      testTargets:
        - CompanySystem-iOSTests
    info:
      properties:
        UILaunchStoryboardName: LaunchView

  CompanySystem-iOSTests:
    templates:
      - test
    sources:
      - AppTests
    dependencies:
      - target: CompanySystem-iOS

  